server:
  port: 8888

spring:
  application:
    name: gateway-server
  config:
    import: configserver:${CONFIG_URI:http://localhost:8787}
  cloud:
    gateway:
      routes:
        - id: discovery-service-route
          uri: lb://discovery-service
          predicates:
            - Path=/api/v1/discovery/**

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
