spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DogacUlgacc/Smart-spend
          # default-label: main
          search-paths:
            - config-server
            - configurations/
            - configurations/{application}

server:
  port: 8787
